[package]
name = "nsncd"
version = "0.1.0"
authors = ["Leif Walsh <leif.walsh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
atoi = "^0.3"
slog = "^2.5"
slog-async = "^2.5"
slog-term = "^2.6"
nix = "^0.18"
#nix = { git = "https://github.com/blinsay/nix.git", branch = "master" }
num-derive = "^0.2"
num-traits = "^0.2"
systemd = "^0.6"

[dev-dependencies]
criterion = "^0.3"

[[bench]]
name = "user"
harness = false