name: "Debian 10"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:10

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get -y install build-essential dpkg-dev ca-certificates
        apt-get -y build-dep .
    - name: Build
      run: cargo build --verbose
