name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy
    - name: Install dependencies
      run: |
        echo deb http://archive.ubuntu.com/ubuntu bionic-backports main universe| sudo tee /etc/apt/sources.list.d/backports.list
        sudo apt-get update
        sudo apt-get install build-essential dpkg-dev
        sudo apt-get -t bionic-backports build-dep .
    - name: CI
      run: ci/test.sh
